#!/bin/bash
# List explicitly installed packages by size excluding the size of their dependencies
# - excludes packages from base and base-devel groups
# Source: https://wiki.archlinux.org/index.php/Pacman/Tips_and_tricks#With_size
# Dropped '-n' from Pacman options to include AUR packages
expac -H M '%011m\t%-20n\t%10d' $(comm -23 <(pacman -Qqe | sort) <(pacman -Qqg base base-devel | sort)) | sort -n
